CREATE TABLE game (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    LAUNCHER_ID BIGINT NULL,
    GAME_STATUS_ENUM NVARCHAR(25) NOT NULL,
    FINISH_DATE DATE NULL,
    ONE_HUNDRED_PERCENT_DATE DATE NULL,
    IMAGE_URL NVARCHAR(300),
    STATUS BIT NOT NULL,

    CONSTRAINT FK_GAME_LAUNCHER FOREIGN KEY (LAUNCHER_ID) REFERENCES launcher(ID)
);