CREATE TABLE rating (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    GAMEPLAY DECIMAL(4,2) NOT NULL,
    GRAPHICS DECIMAL(4,2) NOT NULL,
    SOUND DECIMAL(4,2) NOT NULL,
    STORY DECIMAL(4,2) NOT NULL,
    PERFORMANCE DECIMAL(4,2) NOT NULL,
    AVERAGE DECIMAL(4,2) NOT NULL,
    STATUS BIT NULL
);